### ISSUE TITLE
Prepopulating model

### ISSUE THREAD

**Issue by Knuckles9090** [networknt/angular-schema-form-ui-select#14] opened 2015-04-06 16:55 UTC
I noticed that if I prepopulate a model containing an multiselect array, the input element on the form is not filled with with the model elements.

Kind regards,
Knuckles

**Comment by damogallagher** [comment] 2015-04-06 22:06
Hi Knuckles9090

Could you post your schema form and code please till I have a look?
I have done this in the past and it worked no problem

**Comment by stevehu** [comment] 2015-04-07 00:09
@Knuckles9090 You can find some of my forms in the following folder.
https://github.com/networknt/light/tree/master/server/src/main/resources/form
And the code to pre-populate form dropdown values is here.
https://github.com/networknt/light/blob/master/rule/src/main/java/com/networknt/light/rule/form/GetFormRule.java

Also, I have a new repo called angular-scheam-form-uiselect and there is a demo you can run on your local server and connect to my server for form as well as dropdowns.

**Comment by stevehu** [comment] 2015-04-24 12:54
@Knuckles9090 Could you please confirm if the issue is resolved in angular-schema-form-uiselect? Thanks.

**Comment by Knuckles9090** [comment] 2015-04-24 15:13
I´ll test it out again tomorrow.

**Closed** 2015-04-27 10:43 UTC
